Fix: Change sets to tuples to support concatenation
TypeError: unsupported operand type(s) for +: 'set' and 'set'

Sets don't support + operator in Python. Changed to tuples which do:
- ALLOWED_IMAGE_TYPES: tuple[str, ...]
- ALLOWED_VIDEO_TYPES: tuple[str, ...]
- ALLOWED_UPLOAD_EXTENSIONS: tuple[str, ...]

This allows validators.py to concatenate them with + operator.